name: GHPages

on:
  push:
    branches: [master]

jobs:
  deploy-docs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 10.30.1
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: pnpm
    - name: Install Packages
      run: pnpm install --frozen-lockfile
    - name: Build all
      run: pnpm run build
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        force_orphan: true
