name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lintAndTest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install Packages
      run: |+
        npm ci
        npm run ci:all
    - name: Lint
      run: |+
        npm run lint
        npm run check
    - name: Build
      run: npm run build:ci
    - name: Test
      run: npm test
