name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 10.30.1
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: pnpm
    - name: Install Packages
      run: pnpm install --frozen-lockfile
    - name: Lint
      run: |+
        pnpm run lint
        pnpm run check
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 10.30.1
    - uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: pnpm
    - name: Install Packages
      run: pnpm install --frozen-lockfile
    - name: Build
      run: pnpm run build:ci
    - name: Test
      run: pnpm test
